### PR TITLE
Extended Show commands

### PR DESCRIPTION
**Pull request by stettberger**
Ask me in the office

### CODE REVIEW

**Comment by gregkh** [comment]
Best pull request comment ever...

**Comment by vrothberg** [comment]
Now I had to laugh two times, thanks guys =)

**Comment by stettberger** [comment]
Ok, now the show command system is a little better decomposed into single commits.

**Comment by vrothberg** [comment]
I'm getting through the code at the moment and am playing around with it...awesome!

If you find some time, would you fix the introduced pylint warnings?   For me one big commit fixing pylint stuff would be fine.

**Comment by stettberger** [comment]
Ok, I also added three "please stop complaining" lines. Are they ok for you?

**Comment by vrothberg** [comment]
Thanks!  I prefer to disable pylint warning locally (i.e., in affected methodes, classes, etc.) as global disabling can hide later issues.

**Comment by stettberger** [comment]
I removed those lines

**Pull request merged**
