### PR TITLE
vgrep: add '?' support to -s

### PR DESCRIPTION
**Pull request by gregkh**
Sometimes you just want to see the help command again, and if you have
already typed a command, you can no longer do that.  So add support for
'?' to be a valid option to show the help again.

### CODE REVIEW

**Comment by gregkh** [comment]
Note, this might not be the best way to support it, and it's totally undocumented, but I figured it was a start to the conversation about it.

**Comment by vrothberg** [comment]
I like it.  Would you mind adding a note to the README?

Thanks!

**Comment by gregkh** [comment]
Argh, sorry, this was still on my todo list to fix up, many thanks for merging it as-is, I owe you a beer...

**Comment by vrothberg** [comment]
Really no problem!  Getting patches and beer sounds great =)

**Pull request merged**
