### PR TITLE
interactive: switch from bufio Scanner to (readline-like) liner

### PR DESCRIPTION
**Pull request by Qeole**
Use the liner Go library to process commands in interactive mode. It provides better support for input (such as directional arrows) and a number of classic readline [shortcuts](https://github.com/peterh/liner#line-editing). It also does command history, which can be handy for editing the range of a previous command for example. Autocompletion also exists but is not implemented in this commit (the one-letter commands hardly need any completion).

Drawback: This obviously adds a dependency. Although I believe it really makes interactive mode more user-friendly, I would understand if this change is undesirable.

---

Edit: Based on the discussion, I switched from `readline` library to `liner`

### CODE REVIEW

**Comment by vrothberg** [comment]
https://github.com/manifoldco/promptui could be a good candidate.

**Comment by vrothberg** [comment]
> https://github.com/manifoldco/promptui could be a good candidate.

Nope: that's actually using readline

> github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48

**Comment by Qeole** [comment]
Right, I didn't notice it was unmaintained. In one [issue](https://github.com/chzyer/readline/issues/178#issuecomment-568419897) of the project people mention [liner](https://github.com/peterh/liner) (although it does not look so active either :/), I haven't tried it yet but could have a look if you think it is any better.

**Comment by vrothberg** [comment]
> Right, I didn't notice it was unmaintained. In one [issue](https://github.com/chzyer/readline/issues/178#issuecomment-568419897) of the project people mention [liner](https://github.com/peterh/liner) (although it does not look so active either :/), I haven't tried it yet but could have a look if you think it is any better.

liner looks good to me. The last release was in Dec '19 and it's on go modules with a single dependency:
> require github.com/mattn/go-runewidth v0.0.3

Let's jump on liner and get this PR merged? Once in, we can rebase https://github.com/vrothberg/vgrep/pull/108 and get that in as well.

**Comment by Qeole** [comment]
I switched to liner. Note that **we lose bold marking** for the prompt (`Enter a vgrep command: `) with this library, ANSI control codes are [rejected on purpose](https://github.com/peterh/liner/commit/160e3795572865ddd53357b3c3744fef57925885) to prevent compatibility issues with Windows. I could find no easy workaround. We can print a bold marker before the prompt but in that case we cannot “close” it before user input.

Other than that the command line gets better, history works too. Still no autocompletion added. History could be written to a file (and read again on next vgrep invocation) but I didn't think it necessary and didn't implement it. Minor difference with readline, the prompt is still displayed when reading from a heredoc (as for the tests), but this is not an issue. I could enable status check for the test though, which is good.

**Comment by Qeole** [comment]
Playing a little bit with the readline (to rebase the other PR), it seems it leaves the terminal in a weird state somehow. Typing `Enter` on later prompts from other command lines (e.g. `git add -p` or typing SSH key password) does not seem to work well. I'm using Zsh and maybe it impacts just this but still, there's probably a bug somewhere, I'll try to dig a bit more.

**Comment by Qeole** [comment]
Follow-up: This is likely because the `defer line.Close()` is not executed if we hit `Ctrl-D` or `Ctrl-C` and we `os.Exit(1)` immediately. I'll send a fix as part as the other PR.

**Pull request merged**
