### PR TITLE
Modify fzf example; parse error due to typo

### PR DESCRIPTION
**Pull request by gbraad**

### CODE REVIEW

**Comment by gbraad** [comment]
image

image

**Comment by vrothberg** [comment]
Thanks!  I have never used fzf, and have no experience in using it.  @SuperSandro2000 is the specialist and know what's going on.

**Review by vrothberg — APPROVED** [review]
Merging since it's clearly fixing an issue.  We can tackle the remainder later.
Thanks!

**Comment by SuperSandro2000** [comment]
Probably a copy paste error on my side.

**Pull request merged**
