### PR TITLE
Swap Index and File in IDE mode.

### PR DESCRIPTION
**Pull request by cfelder**
otherwise it is not possible to click on file:lineno in JetBrains IDEs

### CODE REVIEW

**Comment by vrothberg** [comment]
Thanks for the PR!

I just tested jetbrains-idea-ce and indeed it doesn't open the links.  However, it also doesn't open when using the PR.  I played a bit `echo`ing `path:line` but the idea-ce terminal didn't like any of them.

Which IDE are you using?

**Comment by cfelder** [comment]
I tested with the following IDEs

PyCharm 2020.2 Professional
```
$ echo $TERMINAL_EMULATOR
JetBrains-JediTerm
```

Goland 2020.3.1
```
$ echo $TERMINAL_EMULATOR
JetBrains-JediTerm
```

**Comment by cfelder** [comment]
I just noticed that the items are just clickable when the paths are relative to your project root.

If you change into subdirectories the items are not clickable anymore as they are relative to cwd.

**Comment by vrothberg** [comment]
> I just noticed that the items are just clickable when the paths are relative to your project root.
> 
> If you change into subdirectories the items are not clickable anymore as they are relative to cwd.

Good catch!  Thanks a ton for looking into it.

It seems there's nothing vgrep can do, right?

**Comment by cfelder** [comment]
> It seems there's nothing vgrep can do, right?

Without knowing the project root which is not in an environment variable I don't think there is much vgrep can do

beside improving the situation when being in project root using this PR.

**Comment by vrothberg** [comment]
> > It seems there's nothing vgrep can do, right?
> 
> Without knowing the project root which is not in an environment variable I don't think there is much vgrep can do
> 
> beside improving the situation when being in project root using this PR.

I had another look and it doesn't work for me even when being in the project root.  I am under the impression that the jetbrains IDE is _very_ picky ^^

**Comment by cfelder** [comment]
> I had another look and it doesn't work for me even when being in the project root. I am under the impression that the jetbrains IDE is _very_ picky ^^

Fair enough.

What do you think about adding a ``--output-format=XXX`` with a format string to define which columns are printed in which order?

One could alias this to redefine the output of columns.

**Comment by cfelder** [comment]
Could be implemented using [strings.Replacer](https://golang.org/pkg/strings/#Replacer):

similar to python format function using the following labels:

* ``{Index}``
* ``{File}``
* ``{Line}``
* ``{Content}``

e.g. ``--output-format="{File} {Index} {Line} {Content}"`` for an alternative format

**Comment by vrothberg** [comment]
Sorry for the very late reply.  I would try to avoid adding new flags to vgrep if possible.  Do you know what jetbrains needs exactly? I'm still not 100 percent sure.

**Comment by vrothberg** [comment]
I am going to close.  Feel free to reopen at any time.

**Pull request closed without merging**
